/*-
 * Copyright (c) 2018, 2026 Oracle and/or its affiliates. All rights reserved.
 *
 * Licensed under the Universal Permissive License v 1.0 as shown at
 *  https://oss.oracle.com/licenses/upl/
 */

'use strict';

const Enum = require('./constants').Enum;

/**
 * Cloud service only.
 * <p>
 * This enumeration lists all regions available for Oracle NoSQL Database
 * Cloud Service.
 * [This page]{@link https://docs.cloud.oracle.com/iaas/Content/General/Concepts/regions.htm}
 * provides information about Oracle Cloud Infrastracture regions,
 * availability domains and realms.
 * <p>
 * You may use {@link Region} to provide the service endpoint by specifying
 * {@link Config}#region instead of {@link Config}#endpoint. The endpoint will
 * be inferred from the region. Use of a {@link Region} instance is preferred
 * to an endpoint.
 * <p>
 * The string-based endpoints associated with regions for the Oracle NoSQL
 * Database Cloud Service are of the format
 * <pre>    https://nosql.{region}.oci.{secondLevelDomain} </pre>
 * Examples of known second level domains include:
 * <ul>
 * <li>oraclecloud.com</li>
 * <li>oraclegovcloud.com</li>
 * <li>oraclegovcloud.uk</li>
 * </ul>
 * For example, this is a valid endpoint for the Oracle NoSQL Database Cloud
 * Service in the U.S. East region
 * <pre>    nosql.us-ashburn-1.oci.oraclecloud.com </pre>
 * If the Oracle NoSQL Database Cloud Service becomes available in a region
 * not listed here it is possible to connect to that region by setting
 * {@link Config}#endpoint to the endpoint string.
 *
 * @extends Enum
 * @hideconstructor
 *
 * @see {@link Config}
 */
class Region extends Enum {
    constructor(regionId, regionCode, realm) {
        super();
        this._regionId = regionId;
        this._regionCode = regionCode;
        this._realm = realm;
    }

    //currently only called by Config._init()
    static fromRegionId(regionId) {
        return Region[regionId.replace(/-/g, '_').toUpperCase()];
    }

    static fromRegionCodeOrId(regionCodeOrId) {
        const res = Region.find(r =>
            r._regionCode === regionCodeOrId.toLowerCase());
        return res != null ? res : Region.fromRegionId(regionCodeOrId);
    }

    get regionId() {
        return this._regionId;
    }

    get regionCode() {
        return this._regionCode;
    }

    get secondLevelDomain() {
        return this._realm.secondLevelDomain;
    }

    /**
     * NoSQL service endpoint for this region.
     * @type {string}
     * @readonly
     */
    get endpoint() {
        return `https://nosql.${this._regionId}.oci.${this._realm.secondLevelDomain}`;
    }

    toString() {
        return this._regionId;
    }
}

/* === Begin autogenerated realms and regions === */

const Realms = {
    OC0: {
        realmId: 'oc0',
        secondLevelDomain: 'oraclecloud0.com'
    },
    OC1: {
        realmId: 'oc1',
        secondLevelDomain: 'oraclecloud.com'
    },
    OC2: {
        realmId: 'oc2',
        secondLevelDomain: 'oraclegovcloud.com'
    },
    OC3: {
        realmId: 'oc3',
        secondLevelDomain: 'oraclegovcloud.com'
    },
    OC4: {
        realmId: 'oc4',
        secondLevelDomain: 'oraclegovcloud.uk'
    },
    OC5: {
        realmId: 'oc5',
        secondLevelDomain: 'oraclecloud5.com'
    },
    OC6: {
        realmId: 'oc6',
        secondLevelDomain: 'oraclecloud.ic.gov'
    },
    OC8: {
        realmId: 'oc8',
        secondLevelDomain: 'oraclecloud8.com'
    },
    OC9: {
        realmId: 'oc9',
        secondLevelDomain: 'oraclecloud9.com'
    },
    OC10: {
        realmId: 'oc10',
        secondLevelDomain: 'oraclecloud10.com'
    },
    OC11: {
        realmId: 'oc11',
        secondLevelDomain: 'oraclecloud.smil.mil'
    },
    OC12: {
        realmId: 'oc12',
        secondLevelDomain: 'oracledodcloud.ic.gov'
    },
    OC14: {
        realmId: 'oc14',
        secondLevelDomain: 'oraclecloud14.com'
    },
    OC15: {
        realmId: 'oc15',
        secondLevelDomain: 'oraclecloud15.com'
    },
    OC16: {
        realmId: 'oc16',
        secondLevelDomain: 'oraclecloud16.com'
    },
    OC17: {
        realmId: 'oc17',
        secondLevelDomain: 'oraclecloud17.com'
    },
    OC19: {
        realmId: 'oc19',
        secondLevelDomain: 'oraclecloud.eu'
    },
    OC20: {
        realmId: 'oc20',
        secondLevelDomain: 'oraclecloud20.com'
    },
    OC21: {
        realmId: 'oc21',
        secondLevelDomain: 'oraclecloud21.com'
    },
    OC22: {
        realmId: 'oc22',
        secondLevelDomain: 'psn-pco.it'
    },
    OC23: {
        realmId: 'oc23',
        secondLevelDomain: 'oraclecloud23.com'
    },
    OC24: {
        realmId: 'oc24',
        secondLevelDomain: 'oraclecloud24.com'
    },
    OC25: {
        realmId: 'oc25',
        secondLevelDomain: 'nricloud.jp'
    },
    OC26: {
        realmId: 'oc26',
        secondLevelDomain: 'oraclecloud26.com'
    },
    OC27: {
        realmId: 'oc27',
        secondLevelDomain: 'oraclecloud27.com'
    },
    OC28: {
        realmId: 'oc28',
        secondLevelDomain: 'oraclecloud28.com'
    },
    OC29: {
        realmId: 'oc29',
        secondLevelDomain: 'oraclecloud29.com'
    },
    OC31: {
        realmId: 'oc31',
        secondLevelDomain: 'sovereigncloud.nz'
    },
    OC32: {
        realmId: 'oc32',
        secondLevelDomain: 'oraclecloud32.com'
    },
    OC35: {
        realmId: 'oc35',
        secondLevelDomain: 'oraclecloud35.com'
    },
    OC36: {
        realmId: 'oc36',
        secondLevelDomain: 'stccloud.com'
    },
    OC39: {
        realmId: 'oc39',
        secondLevelDomain: 'oraclecloud39.com'
    },
    OC40: {
        realmId: 'oc40',
        secondLevelDomain: 'jpsovereigncloud.jp'
    },
    OC41: {
        realmId: 'oc41',
        secondLevelDomain: 'dutechcloud.ae'
    },
    OC42: {
        realmId: 'oc42',
        secondLevelDomain: 'oraclecloud42.com'
    },
    OC43: {
        realmId: 'oc43',
        secondLevelDomain: 'thaiaiscloud.com'
    },
    OC45: {
        realmId: 'oc45',
        secondLevelDomain: 'q8-onecloud.com'
    },
    OC46: {
        realmId: 'oc46',
        secondLevelDomain: 'oraclecloud46.com'
    },
    OC47: {
        realmId: 'oc47',
        secondLevelDomain: 'oraclecloud47.com'
    },
    OC50: {
        realmId: 'oc50',
        secondLevelDomain: 'opencanvas.jp'
    },
    OC51: {
        realmId: 'oc51',
        secondLevelDomain: 'oraclecloud51.com'
    },
    OC52: {
        realmId: 'oc52',
        secondLevelDomain: 'oraclecloud52.com'
    },
    OC54: {
        realmId: 'oc54',
        secondLevelDomain: 'portalclarocco.com.br'
    },
    OC55: {
        realmId: 'oc55',
        secondLevelDomain: 'svcl.jp'
    },
    OC57: {
        realmId: 'oc57',
        secondLevelDomain: 'eonecloud.com'
    },
    OC60: {
        realmId: 'oc60',
        secondLevelDomain: 'oraclecloud60.com'
    },
    OC61: {
        realmId: 'oc61',
        secondLevelDomain: 'oraclecloud61.com'
    },
    OC62: {
        realmId: 'oc62',
        secondLevelDomain: 'oraclecloud62.com'
    },
    OC64: {
        realmId: 'oc64',
        secondLevelDomain: 'absonne4cloud.com'
    },
    OC88: {
        realmId: 'oc88',
        secondLevelDomain: 'oraclecloud88.com'
    },
};

/**
 * Realm: OC0, RegionID: uk-london-9, RegionKey: AEJ
 */
Region.UK_LONDON_9 = new Region('uk-london-9', 'aej', Realms.OC0);

/**
 * Realm: OC0, RegionID: us-renton-1, RegionKey: RNT
 */
Region.US_RENTON_1 = new Region('us-renton-1', 'rnt', Realms.OC0);

/**
 * Realm: OC0, RegionID: us-scottsdale-1, RegionKey: SCF
 */
Region.US_SCOTTSDALE_1 = new Region('us-scottsdale-1', 'scf', Realms.OC0);

/**
 * Realm: OC1, RegionID: af-casablanca-1, RegionKey: LEJ
 */
Region.AF_CASABLANCA_1 = new Region('af-casablanca-1', 'lej', Realms.OC1);

/**
 * Realm: OC1, RegionID: af-johannesburg-1, RegionKey: JNB
 */
Region.AF_JOHANNESBURG_1 = new Region('af-johannesburg-1', 'jnb', Realms.OC1);

/**
 * Realm: OC1, RegionID: af-nairobi-1, RegionKey: KXT
 */
Region.AF_NAIROBI_1 = new Region('af-nairobi-1', 'kxt', Realms.OC1);

/**
 * Realm: OC1, RegionID: ap-batam-1, RegionKey: HSG
 */
Region.AP_BATAM_1 = new Region('ap-batam-1', 'hsg', Realms.OC1);

/**
 * Realm: OC1, RegionID: ap-chennai-1, RegionKey: DES
 */
Region.AP_CHENNAI_1 = new Region('ap-chennai-1', 'des', Realms.OC1);

/**
 * Realm: OC1, RegionID: ap-chuncheon-1, RegionKey: YNY
 */
Region.AP_CHUNCHEON_1 = new Region('ap-chuncheon-1', 'yny', Realms.OC1);

/**
 * Realm: OC1, RegionID: ap-delhi-1, RegionKey: ONM
 */
Region.AP_DELHI_1 = new Region('ap-delhi-1', 'onm', Realms.OC1);

/**
 * Realm: OC1, RegionID: ap-hyderabad-1, RegionKey: HYD
 */
Region.AP_HYDERABAD_1 = new Region('ap-hyderabad-1', 'hyd', Realms.OC1);

/**
 * Realm: OC1, RegionID: ap-kulai-1, RegionKey: FYV
 */
Region.AP_KULAI_1 = new Region('ap-kulai-1', 'fyv', Realms.OC1);

/**
 * Realm: OC1, RegionID: ap-kulai-2, RegionKey: JBP
 */
Region.AP_KULAI_2 = new Region('ap-kulai-2', 'jbp', Realms.OC1);

/**
 * Realm: OC1, RegionID: ap-melbourne-1, RegionKey: MEL
 */
Region.AP_MELBOURNE_1 = new Region('ap-melbourne-1', 'mel', Realms.OC1);

/**
 * Realm: OC1, RegionID: ap-mumbai-1, RegionKey: BOM
 */
Region.AP_MUMBAI_1 = new Region('ap-mumbai-1', 'bom', Realms.OC1);

/**
 * Realm: OC1, RegionID: ap-osaka-1, RegionKey: KIX
 */
Region.AP_OSAKA_1 = new Region('ap-osaka-1', 'kix', Realms.OC1);

/**
 * Realm: OC1, RegionID: ap-seoul-1, RegionKey: ICN
 */
Region.AP_SEOUL_1 = new Region('ap-seoul-1', 'icn', Realms.OC1);

/**
 * Realm: OC1, RegionID: ap-singapore-1, RegionKey: SIN
 */
Region.AP_SINGAPORE_1 = new Region('ap-singapore-1', 'sin', Realms.OC1);

/**
 * Realm: OC1, RegionID: ap-singapore-2, RegionKey: XSP
 */
Region.AP_SINGAPORE_2 = new Region('ap-singapore-2', 'xsp', Realms.OC1);

/**
 * Realm: OC1, RegionID: ap-sydney-1, RegionKey: SYD
 */
Region.AP_SYDNEY_1 = new Region('ap-sydney-1', 'syd', Realms.OC1);

/**
 * Realm: OC1, RegionID: ap-tokyo-1, RegionKey: NRT
 */
Region.AP_TOKYO_1 = new Region('ap-tokyo-1', 'nrt', Realms.OC1);

/**
 * Realm: OC1, RegionID: ca-montreal-1, RegionKey: YUL
 */
Region.CA_MONTREAL_1 = new Region('ca-montreal-1', 'yul', Realms.OC1);

/**
 * Realm: OC1, RegionID: ca-toronto-1, RegionKey: YYZ
 */
Region.CA_TORONTO_1 = new Region('ca-toronto-1', 'yyz', Realms.OC1);

/**
 * Realm: OC1, RegionID: eu-amsterdam-1, RegionKey: AMS
 */
Region.EU_AMSTERDAM_1 = new Region('eu-amsterdam-1', 'ams', Realms.OC1);

/**
 * Realm: OC1, RegionID: eu-dublin-3, RegionKey: ZQO
 */
Region.EU_DUBLIN_3 = new Region('eu-dublin-3', 'zqo', Realms.OC1);

/**
 * Realm: OC1, RegionID: eu-frankfurt-1, RegionKey: FRA
 */
Region.EU_FRANKFURT_1 = new Region('eu-frankfurt-1', 'fra', Realms.OC1);

/**
 * Realm: OC1, RegionID: eu-madrid-1, RegionKey: MAD
 */
Region.EU_MADRID_1 = new Region('eu-madrid-1', 'mad', Realms.OC1);

/**
 * Realm: OC1, RegionID: eu-madrid-3, RegionKey: ORF
 */
Region.EU_MADRID_3 = new Region('eu-madrid-3', 'orf', Realms.OC1);

/**
 * Realm: OC1, RegionID: eu-marseille-1, RegionKey: MRS
 */
Region.EU_MARSEILLE_1 = new Region('eu-marseille-1', 'mrs', Realms.OC1);

/**
 * Realm: OC1, RegionID: eu-milan-1, RegionKey: LIN
 */
Region.EU_MILAN_1 = new Region('eu-milan-1', 'lin', Realms.OC1);

/**
 * Realm: OC1, RegionID: eu-paris-1, RegionKey: CDG
 */
Region.EU_PARIS_1 = new Region('eu-paris-1', 'cdg', Realms.OC1);

/**
 * Realm: OC1, RegionID: eu-stockholm-1, RegionKey: ARN
 */
Region.EU_STOCKHOLM_1 = new Region('eu-stockholm-1', 'arn', Realms.OC1);

/**
 * Realm: OC1, RegionID: eu-turin-1, RegionKey: NRQ
 */
Region.EU_TURIN_1 = new Region('eu-turin-1', 'nrq', Realms.OC1);

/**
 * Realm: OC1, RegionID: eu-zurich-1, RegionKey: ZRH
 */
Region.EU_ZURICH_1 = new Region('eu-zurich-1', 'zrh', Realms.OC1);

/**
 * Realm: OC1, RegionID: il-jerusalem-1, RegionKey: MTZ
 */
Region.IL_JERUSALEM_1 = new Region('il-jerusalem-1', 'mtz', Realms.OC1);

/**
 * Realm: OC1, RegionID: me-abudhabi-1, RegionKey: AUH
 */
Region.ME_ABUDHABI_1 = new Region('me-abudhabi-1', 'auh', Realms.OC1);

/**
 * Realm: OC1, RegionID: me-dubai-1, RegionKey: DXB
 */
Region.ME_DUBAI_1 = new Region('me-dubai-1', 'dxb', Realms.OC1);

/**
 * Realm: OC1, RegionID: me-jeddah-1, RegionKey: JED
 */
Region.ME_JEDDAH_1 = new Region('me-jeddah-1', 'jed', Realms.OC1);

/**
 * Realm: OC1, RegionID: me-riyadh-1, RegionKey: RUH
 */
Region.ME_RIYADH_1 = new Region('me-riyadh-1', 'ruh', Realms.OC1);

/**
 * Realm: OC1, RegionID: mx-monterrey-1, RegionKey: MTY
 */
Region.MX_MONTERREY_1 = new Region('mx-monterrey-1', 'mty', Realms.OC1);

/**
 * Realm: OC1, RegionID: mx-queretaro-1, RegionKey: QRO
 */
Region.MX_QUERETARO_1 = new Region('mx-queretaro-1', 'qro', Realms.OC1);

/**
 * Realm: OC1, RegionID: sa-bogota-1, RegionKey: BOG
 */
Region.SA_BOGOTA_1 = new Region('sa-bogota-1', 'bog', Realms.OC1);

/**
 * Realm: OC1, RegionID: sa-riodejaneiro-2, RegionKey: SWQ
 */
Region.SA_RIODEJANEIRO_2 = new Region('sa-riodejaneiro-2', 'swq', Realms.OC1);

/**
 * Realm: OC1, RegionID: sa-santiago-1, RegionKey: SCL
 */
Region.SA_SANTIAGO_1 = new Region('sa-santiago-1', 'scl', Realms.OC1);

/**
 * Realm: OC1, RegionID: sa-saopaulo-1, RegionKey: GRU
 */
Region.SA_SAOPAULO_1 = new Region('sa-saopaulo-1', 'gru', Realms.OC1);

/**
 * Realm: OC1, RegionID: sa-valparaiso-1, RegionKey: VAP
 */
Region.SA_VALPARAISO_1 = new Region('sa-valparaiso-1', 'vap', Realms.OC1);

/**
 * Realm: OC1, RegionID: sa-vinhedo-1, RegionKey: VCP
 */
Region.SA_VINHEDO_1 = new Region('sa-vinhedo-1', 'vcp', Realms.OC1);

/**
 * Realm: OC1, RegionID: uk-cardiff-1, RegionKey: CWL
 */
Region.UK_CARDIFF_1 = new Region('uk-cardiff-1', 'cwl', Realms.OC1);

/**
 * Realm: OC1, RegionID: uk-london-1, RegionKey: LHR
 */
Region.UK_LONDON_1 = new Region('uk-london-1', 'lhr', Realms.OC1);

/**
 * Realm: OC1, RegionID: us-abilene-1, RegionKey: ABL
 */
Region.US_ABILENE_1 = new Region('us-abilene-1', 'abl', Realms.OC1);

/**
 * Realm: OC1, RegionID: us-ashburn-1, RegionKey: IAD
 */
Region.US_ASHBURN_1 = new Region('us-ashburn-1', 'iad', Realms.OC1);

/**
 * Realm: OC1, RegionID: us-boardman-1, RegionKey: NHJ
 */
Region.US_BOARDMAN_1 = new Region('us-boardman-1', 'nhj', Realms.OC1);

/**
 * Realm: OC1, RegionID: us-chicago-1, RegionKey: ORD
 */
Region.US_CHICAGO_1 = new Region('us-chicago-1', 'ord', Realms.OC1);

/**
 * Realm: OC1, RegionID: us-columbus-1, RegionKey: VKZ
 */
Region.US_COLUMBUS_1 = new Region('us-columbus-1', 'vkz', Realms.OC1);

/**
 * Realm: OC1, RegionID: us-dallas-1, RegionKey: DFW
 */
Region.US_DALLAS_1 = new Region('us-dallas-1', 'dfw', Realms.OC1);

/**
 * Realm: OC1, RegionID: us-desmoines-1, RegionKey: KQQ
 */
Region.US_DESMOINES_1 = new Region('us-desmoines-1', 'kqq', Realms.OC1);

/**
 * Realm: OC1, RegionID: us-lenexa-1, RegionKey: LXO
 */
Region.US_LENEXA_1 = new Region('us-lenexa-1', 'lxo', Realms.OC1);

/**
 * Realm: OC1, RegionID: us-phoenix-1, RegionKey: PHX
 */
Region.US_PHOENIX_1 = new Region('us-phoenix-1', 'phx', Realms.OC1);

/**
 * Realm: OC1, RegionID: us-quincy-1, RegionKey: EEM
 */
Region.US_QUINCY_1 = new Region('us-quincy-1', 'eem', Realms.OC1);

/**
 * Realm: OC1, RegionID: us-saltlake-2, RegionKey: AGA
 */
Region.US_SALTLAKE_2 = new Region('us-saltlake-2', 'aga', Realms.OC1);

/**
 * Realm: OC1, RegionID: us-sanantonio-1, RegionKey: FBB
 */
Region.US_SANANTONIO_1 = new Region('us-sanantonio-1', 'fbb', Realms.OC1);

/**
 * Realm: OC1, RegionID: us-sanjose-1, RegionKey: SJC
 */
Region.US_SANJOSE_1 = new Region('us-sanjose-1', 'sjc', Realms.OC1);

/**
 * Realm: OC1, RegionID: us-shawnee-1, RegionKey: DRZ
 */
Region.US_SHAWNEE_1 = new Region('us-shawnee-1', 'drz', Realms.OC1);

/**
 * Realm: OC2, RegionID: us-langley-1, RegionKey: LFI
 */
Region.US_LANGLEY_1 = new Region('us-langley-1', 'lfi', Realms.OC2);

/**
 * Realm: OC2, RegionID: us-luke-1, RegionKey: LUF
 */
Region.US_LUKE_1 = new Region('us-luke-1', 'luf', Realms.OC2);

/**
 * Realm: OC3, RegionID: us-gov-ashburn-1, RegionKey: RIC
 */
Region.US_GOV_ASHBURN_1 = new Region('us-gov-ashburn-1', 'ric', Realms.OC3);

/**
 * Realm: OC3, RegionID: us-gov-chicago-1, RegionKey: PIA
 */
Region.US_GOV_CHICAGO_1 = new Region('us-gov-chicago-1', 'pia', Realms.OC3);

/**
 * Realm: OC3, RegionID: us-gov-phoenix-1, RegionKey: TUS
 */
Region.US_GOV_PHOENIX_1 = new Region('us-gov-phoenix-1', 'tus', Realms.OC3);

/**
 * Realm: OC4, RegionID: uk-gov-cardiff-1, RegionKey: BRS
 */
Region.UK_GOV_CARDIFF_1 = new Region('uk-gov-cardiff-1', 'brs', Realms.OC4);

/**
 * Realm: OC4, RegionID: uk-gov-london-1, RegionKey: LTN
 */
Region.UK_GOV_LONDON_1 = new Region('uk-gov-london-1', 'ltn', Realms.OC4);

/**
 * Realm: OC5, RegionID: us-tacoma-1, RegionKey: TIW
 */
Region.US_TACOMA_1 = new Region('us-tacoma-1', 'tiw', Realms.OC5);

/**
 * Realm: OC6, RegionID: us-gov-fortworth-1, RegionKey: FTW
 */
Region.US_GOV_FORTWORTH_1 = new Region('us-gov-fortworth-1', 'ftw', Realms.OC6);

/**
 * Realm: OC6, RegionID: us-gov-sterling-2, RegionKey: DCA
 */
Region.US_GOV_STERLING_2 = new Region('us-gov-sterling-2', 'dca', Realms.OC6);

/**
 * Realm: OC8, RegionID: ap-chiyoda-1, RegionKey: NJA
 */
Region.AP_CHIYODA_1 = new Region('ap-chiyoda-1', 'nja', Realms.OC8);

/**
 * Realm: OC8, RegionID: ap-ibaraki-1, RegionKey: UKB
 */
Region.AP_IBARAKI_1 = new Region('ap-ibaraki-1', 'ukb', Realms.OC8);

/**
 * Realm: OC9, RegionID: me-dcc-muscat-1, RegionKey: MCT
 */
Region.ME_DCC_MUSCAT_1 = new Region('me-dcc-muscat-1', 'mct', Realms.OC9);

/**
 * Realm: OC9, RegionID: me-ibri-1, RegionKey: IBR
 */
Region.ME_IBRI_1 = new Region('me-ibri-1', 'ibr', Realms.OC9);

/**
 * Realm: OC10, RegionID: ap-dcc-canberra-1, RegionKey: WGA
 */
Region.AP_DCC_CANBERRA_1 = new Region('ap-dcc-canberra-1', 'wga', Realms.OC10);

/**
 * Realm: OC11, RegionID: us-gov-fortworth-3, RegionKey: DAL
 */
Region.US_GOV_FORTWORTH_3 = new Region('us-gov-fortworth-3', 'dal', Realms.OC11);

/**
 * Realm: OC11, RegionID: us-gov-phoenix-3, RegionKey: GYR
 */
Region.US_GOV_PHOENIX_3 = new Region('us-gov-phoenix-3', 'gyr', Realms.OC11);

/**
 * Realm: OC11, RegionID: us-gov-sterling-3, RegionKey: HEF
 */
Region.US_GOV_STERLING_3 = new Region('us-gov-sterling-3', 'hef', Realms.OC11);

/**
 * Realm: OC12, RegionID: us-gov-ashburn-2, RegionKey: OKV
 */
Region.US_GOV_ASHBURN_2 = new Region('us-gov-ashburn-2', 'okv', Realms.OC12);

/**
 * Realm: OC12, RegionID: us-gov-phoenix-2, RegionKey: GEU
 */
Region.US_GOV_PHOENIX_2 = new Region('us-gov-phoenix-2', 'geu', Realms.OC12);

/**
 * Realm: OC12, RegionID: us-gov-saltlake-1, RegionKey: VEL
 */
Region.US_GOV_SALTLAKE_1 = new Region('us-gov-saltlake-1', 'vel', Realms.OC12);

/**
 * Realm: OC14, RegionID: eu-dcc-dublin-1, RegionKey: ORK
 */
Region.EU_DCC_DUBLIN_1 = new Region('eu-dcc-dublin-1', 'ork', Realms.OC14);

/**
 * Realm: OC14, RegionID: eu-dcc-dublin-2, RegionKey: SNN
 */
Region.EU_DCC_DUBLIN_2 = new Region('eu-dcc-dublin-2', 'snn', Realms.OC14);

/**
 * Realm: OC14, RegionID: eu-dcc-milan-1, RegionKey: BGY
 */
Region.EU_DCC_MILAN_1 = new Region('eu-dcc-milan-1', 'bgy', Realms.OC14);

/**
 * Realm: OC14, RegionID: eu-dcc-milan-2, RegionKey: MXP
 */
Region.EU_DCC_MILAN_2 = new Region('eu-dcc-milan-2', 'mxp', Realms.OC14);

/**
 * Realm: OC14, RegionID: eu-dcc-rating-1, RegionKey: DUS
 */
Region.EU_DCC_RATING_1 = new Region('eu-dcc-rating-1', 'dus', Realms.OC14);

/**
 * Realm: OC14, RegionID: eu-dcc-rating-2, RegionKey: DTM
 */
Region.EU_DCC_RATING_2 = new Region('eu-dcc-rating-2', 'dtm', Realms.OC14);

/**
 * Realm: OC15, RegionID: ap-dcc-gazipur-1, RegionKey: DAC
 */
Region.AP_DCC_GAZIPUR_1 = new Region('ap-dcc-gazipur-1', 'dac', Realms.OC15);

/**
 * Realm: OC16, RegionID: us-sanjose-2, RegionKey: QKL
 */
Region.US_SANJOSE_2 = new Region('us-sanjose-2', 'qkl', Realms.OC16);

/**
 * Realm: OC16, RegionID: us-westjordan-1, RegionKey: SGU
 */
Region.US_WESTJORDAN_1 = new Region('us-westjordan-1', 'sgu', Realms.OC16);

/**
 * Realm: OC17, RegionID: us-dcc-phoenix-1, RegionKey: IFP
 */
Region.US_DCC_PHOENIX_1 = new Region('us-dcc-phoenix-1', 'ifp', Realms.OC17);

/**
 * Realm: OC17, RegionID: us-dcc-phoenix-2, RegionKey: GCN
 */
Region.US_DCC_PHOENIX_2 = new Region('us-dcc-phoenix-2', 'gcn', Realms.OC17);

/**
 * Realm: OC17, RegionID: us-dcc-phoenix-4, RegionKey: YUM
 */
Region.US_DCC_PHOENIX_4 = new Region('us-dcc-phoenix-4', 'yum', Realms.OC17);

/**
 * Realm: OC19, RegionID: eu-frankfurt-2, RegionKey: STR
 */
Region.EU_FRANKFURT_2 = new Region('eu-frankfurt-2', 'str', Realms.OC19);

/**
 * Realm: OC19, RegionID: eu-madrid-2, RegionKey: VLL
 */
Region.EU_MADRID_2 = new Region('eu-madrid-2', 'vll', Realms.OC19);

/**
 * Realm: OC20, RegionID: eu-jovanovac-1, RegionKey: BEG
 */
Region.EU_JOVANOVAC_1 = new Region('eu-jovanovac-1', 'beg', Realms.OC20);

/**
 * Realm: OC21, RegionID: me-alrayyan-1, RegionKey: VVE
 */
Region.ME_ALRAYYAN_1 = new Region('me-alrayyan-1', 'vve', Realms.OC21);

/**
 * Realm: OC21, RegionID: me-dcc-doha-1, RegionKey: DOH
 */
Region.ME_DCC_DOHA_1 = new Region('me-dcc-doha-1', 'doh', Realms.OC21);

/**
 * Realm: OC22, RegionID: eu-dcc-rome-1, RegionKey: NAP
 */
Region.EU_DCC_ROME_1 = new Region('eu-dcc-rome-1', 'nap', Realms.OC22);

/**
 * Realm: OC22, RegionID: eu-milan-2, RegionKey: PBV
 */
Region.EU_MILAN_2 = new Region('eu-milan-2', 'pbv', Realms.OC22);

/**
 * Realm: OC23, RegionID: us-somerset-1, RegionKey: EBB
 */
Region.US_SOMERSET_1 = new Region('us-somerset-1', 'ebb', Realms.OC23);

/**
 * Realm: OC23, RegionID: us-thames-1, RegionKey: EBL
 */
Region.US_THAMES_1 = new Region('us-thames-1', 'ebl', Realms.OC23);

/**
 * Realm: OC24, RegionID: eu-crissier-1, RegionKey: AVF
 */
Region.EU_CRISSIER_1 = new Region('eu-crissier-1', 'avf', Realms.OC24);

/**
 * Realm: OC24, RegionID: eu-dcc-zurich-1, RegionKey: AVZ
 */
Region.EU_DCC_ZURICH_1 = new Region('eu-dcc-zurich-1', 'avz', Realms.OC24);

/**
 * Realm: OC25, RegionID: ap-dcc-osaka-1, RegionKey: UKY
 */
Region.AP_DCC_OSAKA_1 = new Region('ap-dcc-osaka-1', 'uky', Realms.OC25);

/**
 * Realm: OC25, RegionID: ap-dcc-tokyo-1, RegionKey: TYO
 */
Region.AP_DCC_TOKYO_1 = new Region('ap-dcc-tokyo-1', 'tyo', Realms.OC25);

/**
 * Realm: OC26, RegionID: me-abudhabi-3, RegionKey: AHU
 */
Region.ME_ABUDHABI_3 = new Region('me-abudhabi-3', 'ahu', Realms.OC26);

/**
 * Realm: OC26, RegionID: me-alain-1, RegionKey: RBA
 */
Region.ME_ALAIN_1 = new Region('me-alain-1', 'rba', Realms.OC26);

/**
 * Realm: OC27, RegionID: us-dcc-swjordan-1, RegionKey: OZZ
 */
Region.US_DCC_SWJORDAN_1 = new Region('us-dcc-swjordan-1', 'ozz', Realms.OC27);

/**
 * Realm: OC28, RegionID: us-dcc-swjordan-2, RegionKey: DRS
 */
Region.US_DCC_SWJORDAN_2 = new Region('us-dcc-swjordan-2', 'drs', Realms.OC28);

/**
 * Realm: OC29, RegionID: me-abudhabi-2, RegionKey: RKT
 */
Region.ME_ABUDHABI_2 = new Region('me-abudhabi-2', 'rkt', Realms.OC29);

/**
 * Realm: OC29, RegionID: me-abudhabi-4, RegionKey: SHJ
 */
Region.ME_ABUDHABI_4 = new Region('me-abudhabi-4', 'shj', Realms.OC29);

/**
 * Realm: OC31, RegionID: ap-hobsonville-1, RegionKey: IZQ
 */
Region.AP_HOBSONVILLE_1 = new Region('ap-hobsonville-1', 'izq', Realms.OC31);

/**
 * Realm: OC31, RegionID: ap-silverdale-1, RegionKey: JJT
 */
Region.AP_SILVERDALE_1 = new Region('ap-silverdale-1', 'jjt', Realms.OC31);

/**
 * Realm: OC32, RegionID: ap-olympic-1, RegionKey: ZZM
 */
Region.AP_OLYMPIC_1 = new Region('ap-olympic-1', 'zzm', Realms.OC32);

/**
 * Realm: OC35, RegionID: ap-chuncheon-2, RegionKey: BNO
 */
Region.AP_CHUNCHEON_2 = new Region('ap-chuncheon-2', 'bno', Realms.OC35);

/**
 * Realm: OC35, RegionID: ap-seoul-2, RegionKey: DTZ
 */
Region.AP_SEOUL_2 = new Region('ap-seoul-2', 'dtz', Realms.OC35);

/**
 * Realm: OC35, RegionID: ap-suwon-1, RegionKey: DLN
 */
Region.AP_SUWON_1 = new Region('ap-suwon-1', 'dln', Realms.OC35);

/**
 * Realm: OC36, RegionID: me-alkhobar-1, RegionKey: DAM
 */
Region.ME_ALKHOBAR_1 = new Region('me-alkhobar-1', 'dam', Realms.OC36);

/**
 * Realm: OC36, RegionID: me-riyadh-2, RegionKey: KZQ
 */
Region.ME_RIYADH_2 = new Region('me-riyadh-2', 'kzq', Realms.OC36);

/**
 * Realm: OC39, RegionID: us-tukwila-3, RegionKey: NBQ
 */
Region.US_TUKWILA_3 = new Region('us-tukwila-3', 'nbq', Realms.OC39);

/**
 * Realm: OC40, RegionID: ap-osaka-2, RegionKey: IBG
 */
Region.AP_OSAKA_2 = new Region('ap-osaka-2', 'ibg', Realms.OC40);

/**
 * Realm: OC40, RegionID: ap-tatebayashi-1, RegionKey: JBB
 */
Region.AP_TATEBAYASHI_1 = new Region('ap-tatebayashi-1', 'jbb', Realms.OC40);

/**
 * Realm: OC41, RegionID: me-dubai-2, RegionKey: ABR
 */
Region.ME_DUBAI_2 = new Region('me-dubai-2', 'abr', Realms.OC41);

/**
 * Realm: OC41, RegionID: me-dubai-3, RegionKey: PCZ
 */
Region.ME_DUBAI_3 = new Region('me-dubai-3', 'pcz', Realms.OC41);

/**
 * Realm: OC42, RegionID: us-ashburn-2, RegionKey: YXJ
 */
Region.US_ASHBURN_2 = new Region('us-ashburn-2', 'yxj', Realms.OC42);

/**
 * Realm: OC42, RegionID: us-newark-1, RegionKey: PGC
 */
Region.US_NEWARK_1 = new Region('us-newark-1', 'pgc', Realms.OC42);

/**
 * Realm: OC43, RegionID: ap-pathumthani-1, RegionKey: MEZ
 */
Region.AP_PATHUMTHANI_1 = new Region('ap-pathumthani-1', 'mez', Realms.OC43);

/**
 * Realm: OC43, RegionID: ap-samutprakan-1, RegionKey: YIK
 */
Region.AP_SAMUTPRAKAN_1 = new Region('ap-samutprakan-1', 'yik', Realms.OC43);

/**
 * Realm: OC45, RegionID: me-sabahiya-1, RegionKey: AYZ
 */
Region.ME_SABAHIYA_1 = new Region('me-sabahiya-1', 'ayz', Realms.OC45);

/**
 * Realm: OC46, RegionID: uk-london-2, RegionKey: DEN
 */
Region.UK_LONDON_2 = new Region('uk-london-2', 'den', Realms.OC46);

/**
 * Realm: OC47, RegionID: uk-london-3, RegionKey: KAL
 */
Region.UK_LONDON_3 = new Region('uk-london-3', 'kal', Realms.OC47);

/**
 * Realm: OC47, RegionID: uk-london-4, RegionKey: PYZ
 */
Region.UK_LONDON_4 = new Region('uk-london-4', 'pyz', Realms.OC47);

/**
 * Realm: OC50, RegionID: ap-kyoto-1, RegionKey: SUF
 */
Region.AP_KYOTO_1 = new Region('ap-kyoto-1', 'suf', Realms.OC50);

/**
 * Realm: OC50, RegionID: ap-mitaka-1, RegionKey: MFQ
 */
Region.AP_MITAKA_1 = new Region('ap-mitaka-1', 'mfq', Realms.OC50);

/**
 * Realm: OC51, RegionID: eu-budapest-1, RegionKey: JSK
 */
Region.EU_BUDAPEST_1 = new Region('eu-budapest-1', 'jsk', Realms.OC51);

/**
 * Realm: OC52, RegionID: sa-riodejaneiro-1, RegionKey: HNW
 */
Region.SA_RIODEJANEIRO_1 = new Region('sa-riodejaneiro-1', 'hnw', Realms.OC52);

/**
 * Realm: OC54, RegionID: sa-belenzinho-1, RegionKey: TRX
 */
Region.SA_BELENZINHO_1 = new Region('sa-belenzinho-1', 'trx', Realms.OC54);

/**
 * Realm: OC54, RegionID: sa-saopaulo-3, RegionKey: LMP
 */
Region.SA_SAOPAULO_3 = new Region('sa-saopaulo-3', 'lmp', Realms.OC54);

/**
 * Realm: OC55, RegionID: ap-eastosaka-1, RegionKey: DQF
 */
Region.AP_EASTOSAKA_1 = new Region('ap-eastosaka-1', 'dqf', Realms.OC55);

/**
 * Realm: OC55, RegionID: ap-westtokyo-1, RegionKey: ZWE
 */
Region.AP_WESTTOKYO_1 = new Region('ap-westtokyo-1', 'zwe', Realms.OC55);

/**
 * Realm: OC57, RegionID: me-abudhabi-5, RegionKey: JHZ
 */
Region.ME_ABUDHABI_5 = new Region('me-abudhabi-5', 'jhz', Realms.OC57);

/**
 * Realm: OC57, RegionID: me-dubai-4, RegionKey: ZQA
 */
Region.ME_DUBAI_4 = new Region('me-dubai-4', 'zqa', Realms.OC57);

/**
 * Realm: OC60, RegionID: us-tukwila-5, RegionKey: XAD
 */
Region.US_TUKWILA_5 = new Region('us-tukwila-5', 'xad', Realms.OC60);

/**
 * Realm: OC61, RegionID: us-tukwila-6, RegionKey: XAB
 */
Region.US_TUKWILA_6 = new Region('us-tukwila-6', 'xab', Realms.OC61);

/**
 * Realm: OC62, RegionID: us-tukwila-7, RegionKey: XAC
 */
Region.US_TUKWILA_7 = new Region('us-tukwila-7', 'xac', Realms.OC62);

/**
 * Realm: OC64, RegionID: ap-tokyo-2, RegionKey: JCU
 */
Region.AP_TOKYO_2 = new Region('ap-tokyo-2', 'jcu', Realms.OC64);

/**
 * Realm: OC88, RegionID: ap-olympic-2, RegionKey: JDX
 */
Region.AP_OLYMPIC_2 = new Region('ap-olympic-2', 'jdx', Realms.OC88);

/* === End autogenerated realms and regions === */
Region.seal();

module.exports = Region;
