/*-
 * Copyright (c) 2018, 2024 Oracle and/or its affiliates. All rights reserved.
 *
 * Licensed under the Universal Permissive License v 1.0 as shown at
 *  https://oss.oracle.com/licenses/upl/
 */

import type { Config } from "./config";

/**
 * Cloud service only.
 * <p>
 * This enumeration lists all regions available for Oracle NoSQL Database
 * Cloud Service.
 * {@link https://docs.cloud.oracle.com/iaas/Content/General/Concepts/regions.htm | This page}
 * provides information about Oracle Cloud Infrastracture regions,
 * availability domains and realms.
 * <p>
 * You may use {@link Region} to provide the service endpoint by specifying
 * {@link Config#region} instead of {@link Config#endpoint}. The endpoint will
 * be inferred from the region. Use of a {@link Region} instance is preferred
 * to an endpoint.
 * <p>
 * The string-based endpoints associated with regions for the Oracle NoSQL
 * Database Cloud Service are of the format
 * <pre> https://nosql.\{region\}.oci.\{secondLevelDomain\} </pre>
 * Examples of known second level domains include:
 * <ul>
 * <li>oraclecloud.com</li>
 * <li>oraclegovcloud.com</li>
 * <li>oraclegovcloud.uk</li>
 * </ul>
 * For example, this is a valid endpoint for the Oracle NoSQL Database Cloud
 * Service in the U.S. East region
 * <pre>    nosql.us-ashburn-1.oci.oraclecloud.com </pre>
 * If the Oracle NoSQL Database Cloud Service becomes available in a region
 * not listed here it is possible to connect to that region by setting
 * {@link Config#endpoint} to the endpoint string.
 *
 * @see {@link Config}
 */
export class Region {

    /**
     * @hidden
     */
    private constructor();

    /**
     * Array of all region values.
     */
    static readonly values: Region[];

    /**
     * Get region by region id.
     * @param {string} regionId Region id, e.g. ap-mumbai-1
     * @return {Region} The region, or <em>undefined</em> if given region id
     * is not found.
     */
    static fromRegionId(regionId: string): Region|undefined;

    /**
     * Get region by region code or id.
     * @param {string} regionId Region id, e.g. bom or ap-mumbai-1
     * @return {Region} The region, or <em>undefined</em> if given region code
     * or id is not found.
     */
    static fromRegionCodeOrId(regionCodeOrId: string): Region|undefined;
    
    /**
     * NoSQL service endpoint for this region.
     */
    readonly endpoint: string;

     /**
     * Region id, e.g. <em>ap-mumbai-1</em>.
     */
    readonly regionId: string;
    
    /**
     * Region 3-letter code, e.g. <em>bom</em>.
     */
    readonly regionCode: string;

    /**
     * Second-level domain for the region, e.g. <em>oraclecloud.com</em>.
     */
    readonly secondLevelDomain: string;

    /**
     * Returns string representing this region.
     * @returns String representation, which is {@link regionId}
     */
    toString(): string;

    /* Everything below this line is autogenerated */
    /* === Realms and Regions === */
    /**
     * Realm: OC1, RegionID: af-johannesburg-1, RegionKey: JNB
     */
    static readonly AF_JOHANNESBURG_1: Region;

    /**
     * Realm: OC1, RegionID: ap-chuncheon-1, RegionKey: YNY
     */
    static readonly AP_CHUNCHEON_1: Region;

    /**
     * Realm: OC1, RegionID: ap-hyderabad-1, RegionKey: HYD
     */
    static readonly AP_HYDERABAD_1: Region;

    /**
     * Realm: OC1, RegionID: ap-melbourne-1, RegionKey: MEL
     */
    static readonly AP_MELBOURNE_1: Region;

    /**
     * Realm: OC1, RegionID: ap-mumbai-1, RegionKey: BOM
     */
    static readonly AP_MUMBAI_1: Region;

    /**
     * Realm: OC1, RegionID: ap-osaka-1, RegionKey: KIX
     */
    static readonly AP_OSAKA_1: Region;

    /**
     * Realm: OC1, RegionID: ap-seoul-1, RegionKey: ICN
     */
    static readonly AP_SEOUL_1: Region;

    /**
     * Realm: OC1, RegionID: ap-singapore-1, RegionKey: SIN
     */
    static readonly AP_SINGAPORE_1: Region;

    /**
     * Realm: OC1, RegionID: ap-singapore-2, RegionKey: XSP
     */
    static readonly AP_SINGAPORE_2: Region;

    /**
     * Realm: OC1, RegionID: ap-sydney-1, RegionKey: SYD
     */
    static readonly AP_SYDNEY_1: Region;

    /**
     * Realm: OC1, RegionID: ap-tokyo-1, RegionKey: NRT
     */
    static readonly AP_TOKYO_1: Region;

    /**
     * Realm: OC1, RegionID: ca-montreal-1, RegionKey: YUL
     */
    static readonly CA_MONTREAL_1: Region;

    /**
     * Realm: OC1, RegionID: ca-toronto-1, RegionKey: YYZ
     */
    static readonly CA_TORONTO_1: Region;

    /**
     * Realm: OC1, RegionID: eu-amsterdam-1, RegionKey: AMS
     */
    static readonly EU_AMSTERDAM_1: Region;

    /**
     * Realm: OC1, RegionID: eu-frankfurt-1, RegionKey: FRA
     */
    static readonly EU_FRANKFURT_1: Region;

    /**
     * Realm: OC1, RegionID: eu-madrid-1, RegionKey: MAD
     */
    static readonly EU_MADRID_1: Region;

    /**
     * Realm: OC1, RegionID: eu-marseille-1, RegionKey: MRS
     */
    static readonly EU_MARSEILLE_1: Region;

    /**
     * Realm: OC1, RegionID: eu-milan-1, RegionKey: LIN
     */
    static readonly EU_MILAN_1: Region;

    /**
     * Realm: OC1, RegionID: eu-paris-1, RegionKey: CDG
     */
    static readonly EU_PARIS_1: Region;

    /**
     * Realm: OC1, RegionID: eu-stockholm-1, RegionKey: ARN
     */
    static readonly EU_STOCKHOLM_1: Region;

    /**
     * Realm: OC1, RegionID: eu-zurich-1, RegionKey: ZRH
     */
    static readonly EU_ZURICH_1: Region;

    /**
     * Realm: OC1, RegionID: il-jerusalem-1, RegionKey: MTZ
     */
    static readonly IL_JERUSALEM_1: Region;

    /**
     * Realm: OC1, RegionID: me-abudhabi-1, RegionKey: AUH
     */
    static readonly ME_ABUDHABI_1: Region;

    /**
     * Realm: OC1, RegionID: me-dubai-1, RegionKey: DXB
     */
    static readonly ME_DUBAI_1: Region;

    /**
     * Realm: OC1, RegionID: me-jeddah-1, RegionKey: JED
     */
    static readonly ME_JEDDAH_1: Region;

    /**
     * Realm: OC1, RegionID: me-riyadh-1, RegionKey: RUH
     */
    static readonly ME_RIYADH_1: Region;

    /**
     * Realm: OC1, RegionID: mx-monterrey-1, RegionKey: MTY
     */
    static readonly MX_MONTERREY_1: Region;

    /**
     * Realm: OC1, RegionID: mx-queretaro-1, RegionKey: QRO
     */
    static readonly MX_QUERETARO_1: Region;

    /**
     * Realm: OC1, RegionID: sa-bogota-1, RegionKey: BOG
     */
    static readonly SA_BOGOTA_1: Region;

    /**
     * Realm: OC1, RegionID: sa-santiago-1, RegionKey: SCL
     */
    static readonly SA_SANTIAGO_1: Region;

    /**
     * Realm: OC1, RegionID: sa-saopaulo-1, RegionKey: GRU
     */
    static readonly SA_SAOPAULO_1: Region;

    /**
     * Realm: OC1, RegionID: sa-valparaiso-1, RegionKey: VAP
     */
    static readonly SA_VALPARAISO_1: Region;

    /**
     * Realm: OC1, RegionID: sa-vinhedo-1, RegionKey: VCP
     */
    static readonly SA_VINHEDO_1: Region;

    /**
     * Realm: OC1, RegionID: uk-london-1, RegionKey: LHR
     */
    static readonly UK_LONDON_1: Region;

    /**
     * Realm: OC1, RegionID: uk-cardiff-1, RegionKey: CWL
     */
    static readonly UK_CARDIFF_1: Region;

    /**
     * Realm: OC1, RegionID: us-phoenix-1, RegionKey: PHX
     */
    static readonly US_PHOENIX_1: Region;

    /**
     * Realm: OC1, RegionID: us-ashburn-1, RegionKey: IAD
     */
    static readonly US_ASHBURN_1: Region;

    /**
     * Realm: OC1, RegionID: us-saltlake-2, RegionKey: AGA
     */
    static readonly US_SALTLAKE_2: Region;

    /**
     * Realm: OC1, RegionID: us-sanjose-1, RegionKey: SJC
     */
    static readonly US_SANJOSE_1: Region;

    /**
     * Realm: OC1, RegionID: us-chicago-1, RegionKey: ORD
     */
    static readonly US_CHICAGO_1: Region;

    /**
     * Realm: OC2, RegionID: us-langley-1, RegionKey: LFI
     */
    static readonly US_LANGLEY_1: Region;

    /**
     * Realm: OC2, RegionID: us-luke-1, RegionKey: LUF
     */
    static readonly US_LUKE_1: Region;

    /**
     * Realm: OC5, RegionID: us-tacoma-1, RegionKey: TIW
     */
    static readonly US_TACOMA_1: Region;

    /**
     * Realm: OC8, RegionID: ap-chiyoda-1, RegionKey: NJA
     */
    static readonly AP_CHIYODA_1: Region;

    /**
     * Realm: OC8, RegionID: ap-ibaraki-1, RegionKey: UKB
     */
    static readonly AP_IBARAKI_1: Region;

    /**
     * Realm: OC16, RegionID: us-westjordan-1, RegionKey: SGU
     */
    static readonly US_WESTJORDAN_1: Region;

    /**
     * Realm: OC19, RegionID: eu-frankfurt-2, RegionKey: STR
     */
    static readonly EU_FRANKFURT_2: Region;

    /**
     * Realm: OC19, RegionID: eu-madrid-2, RegionKey: VLL
     */
    static readonly EU_MADRID_2: Region;

    /**
     * Realm: OC20, RegionID: eu-jovanovac-1, RegionKey: BEG
     */
    static readonly EU_JOVANOVAC_1: Region;

    /**
     * Realm: OC23, RegionID: us-somerset-1, RegionKey: EBB
     */
    static readonly US_SOMERSET_1: Region;

    /**
     * Realm: OC23, RegionID: us-thames-1, RegionKey: EBL
     */
    static readonly US_THAMES_1: Region;

    /**
     * Realm: OC24, RegionID: eu-crissier-1, RegionKey: AVF
     */
    static readonly EU_CRISSIER_1: Region;

    /**
     * Realm: OC26, RegionID: me-abudhabi-3, RegionKey: AHU
     */
    static readonly ME_ABUDHABI_3: Region;

    /**
     * Realm: OC26, RegionID: me-alain-1, RegionKey: RBA
     */
    static readonly ME_ALAIN_1: Region;

    /**
     * Realm: OC29, RegionID: me-abudhabi-2, RegionKey: RKT
     */
    static readonly ME_ABUDHABI_2: Region;

    /**
     * Realm: OC29, RegionID: me-abudhabi-4, RegionKey: SHJ
     */
    static readonly ME_ABUDHABI_4: Region;

    /**
     * Realm: OC31, RegionID: ap-hobsonville-1, RegionKey: IZQ
     */
    static readonly AP_HOBSONVILLE_1: Region;

    /**
     * Realm: OC35, RegionID: ap-suwon-1, RegionKey: DLN
     */
    static readonly AP_SUWON_1: Region;

    /**
     * Realm: OC3, RegionID: us-gov-ashburn-1, RegionKey: RIC
     */
    static readonly US_GOV_ASHBURN_1: Region;

    /**
     * Realm: OC3, RegionID: us-gov-chicago-1, RegionKey: PIA
     */
    static readonly US_GOV_CHICAGO_1: Region;

    /**
     * Realm: OC3, RegionID: us-gov-phoenix-1, RegionKey: TUS
     */
    static readonly US_GOV_PHOENIX_1: Region;

    /**
     * Realm: OC4, RegionID: uk-gov-london-1, RegionKey: LTN
     */
    static readonly UK_GOV_LONDON_1: Region;

    /**
     * Realm: OC4, RegionID: uk-gov-cardiff-1, RegionKey: BRS
     */
    static readonly UK_GOV_CARDIFF_1: Region;

    /**
     * Realm: OC9, RegionID: me-dcc-muscat-1, RegionKey: MCT
     */
    static readonly ME_DCC_MUSCAT_1: Region;

    /**
     * Realm: OC10, RegionID: ap-dcc-canberra-1, RegionKey: WGA
     */
    static readonly AP_DCC_CANBERRA_1: Region;

    /**
     * Realm: OC14, RegionID: eu-dcc-dublin-1, RegionKey: ORK
     */
    static readonly EU_DCC_DUBLIN_1: Region;

    /**
     * Realm: OC14, RegionID: eu-dcc-dublin-2, RegionKey: SNN
     */
    static readonly EU_DCC_DUBLIN_2: Region;

    /**
     * Realm: OC14, RegionID: eu-dcc-milan-1, RegionKey: BGY
     */
    static readonly EU_DCC_MILAN_1: Region;

    /**
     * Realm: OC14, RegionID: eu-dcc-milan-2, RegionKey: MXP
     */
    static readonly EU_DCC_MILAN_2: Region;

    /**
     * Realm: OC14, RegionID: eu-dcc-rating-1, RegionKey: DUS
     */
    static readonly EU_DCC_RATING_1: Region;

    /**
     * Realm: OC14, RegionID: eu-dcc-rating-2, RegionKey: DTM
     */
    static readonly EU_DCC_RATING_2: Region;

    /**
     * Realm: OC15, RegionID: ap-dcc-gazipur-1, RegionKey: DAC
     */
    static readonly AP_DCC_GAZIPUR_1: Region;

    /**
     * Realm: OC17, RegionID: us-dcc-phoenix-1, RegionKey: IFP
     */
    static readonly US_DCC_PHOENIX_1: Region;

    /**
     * Realm: OC17, RegionID: us-dcc-phoenix-2, RegionKey: GCN
     */
    static readonly US_DCC_PHOENIX_2: Region;

    /**
     * Realm: OC17, RegionID: us-dcc-phoenix-4, RegionKey: YUM
     */
    static readonly US_DCC_PHOENIX_4: Region;

    /**
     * Realm: OC21, RegionID: me-dcc-doha-1, RegionKey: DOH
     */
    static readonly ME_DCC_DOHA_1: Region;

    /**
     * Realm: OC22, RegionID: eu-dcc-rome-1, RegionKey: NAP
     */
    static readonly EU_DCC_ROME_1: Region;

    /**
     * Realm: OC24, RegionID: eu-dcc-zurich-1, RegionKey: AVZ
     */
    static readonly EU_DCC_ZURICH_1: Region;

    /**
     * Realm: OC25, RegionID: ap-dcc-osaka-1, RegionKey: UKY
     */
    static readonly AP_DCC_OSAKA_1: Region;

    /**
     * Realm: OC25, RegionID: ap-dcc-tokyo-1, RegionKey: TYO
     */
    static readonly AP_DCC_TOKYO_1: Region;

    /**
     * Realm: OC27, RegionID: us-dcc-swjordan-1, RegionKey: OZZ
     */
    static readonly US_DCC_SWJORDAN_1: Region;

    /**
     * Realm: OC28, RegionID: us-dcc-swjordan-2, RegionKey: DRS
     */
    static readonly US_DCC_SWJORDAN_2: Region;

}
