/*-
 * Copyright (c) 2018, 2025 Oracle and/or its affiliates. All rights reserved.
 *
 * Licensed under the Universal Permissive License v 1.0 as shown at
 *  https://oss.oracle.com/licenses/upl/
 */

import type { Config } from "./config";

/**
 * Cloud service only.
 * <p>
 * This enumeration lists all regions available for Oracle NoSQL Database
 * Cloud Service.
 * {@link https://docs.cloud.oracle.com/iaas/Content/General/Concepts/regions.htm | This page}
 * provides information about Oracle Cloud Infrastracture regions,
 * availability domains and realms.
 * <p>
 * You may use {@link Region} to provide the service endpoint by specifying
 * {@link Config#region} instead of {@link Config#endpoint}. The endpoint will
 * be inferred from the region. Use of a {@link Region} instance is preferred
 * to an endpoint.
 * <p>
 * The string-based endpoints associated with regions for the Oracle NoSQL
 * Database Cloud Service are of the format
 * <pre> https://nosql.\{region\}.oci.\{secondLevelDomain\} </pre>
 * Examples of known second level domains include:
 * <ul>
 * <li>oraclecloud.com</li>
 * <li>oraclegovcloud.com</li>
 * <li>oraclegovcloud.uk</li>
 * </ul>
 * For example, this is a valid endpoint for the Oracle NoSQL Database Cloud
 * Service in the U.S. East region
 * <pre>    nosql.us-ashburn-1.oci.oraclecloud.com </pre>
 * If the Oracle NoSQL Database Cloud Service becomes available in a region
 * not listed here it is possible to connect to that region by setting
 * {@link Config#endpoint} to the endpoint string.
 *
 * @see {@link Config}
 */
export class Region {

    /**
     * @hidden
     */
    private constructor();

    /**
     * Array of all region values.
     */
    static readonly values: Region[];

    /**
     * Get region by region id.
     * @param {string} regionId Region id, e.g. ap-mumbai-1
     * @return {Region} The region, or <em>undefined</em> if given region id
     * is not found.
     */
    static fromRegionId(regionId: string): Region|undefined;

    /**
     * Get region by region code or id.
     * @param {string} regionId Region id, e.g. bom or ap-mumbai-1
     * @return {Region} The region, or <em>undefined</em> if given region code
     * or id is not found.
     */
    static fromRegionCodeOrId(regionCodeOrId: string): Region|undefined;
    
    /**
     * NoSQL service endpoint for this region.
     */
    readonly endpoint: string;

     /**
     * Region id, e.g. <em>ap-mumbai-1</em>.
     */
    readonly regionId: string;
    
    /**
     * Region 3-letter code, e.g. <em>bom</em>.
     */
    readonly regionCode: string;

    /**
     * Second-level domain for the region, e.g. <em>oraclecloud.com</em>.
     */
    readonly secondLevelDomain: string;

    /**
     * Returns string representing this region.
     * @returns String representation, which is {@link regionId}
     */
    toString(): string;

    /* === Begin autogenerated realms and regions === */
    /**
     * Realm: OC1, South Africa (Johannesburg)
     */
    static readonly AF_JOHANNESBURG_1: Region;

    /**
     * Realm: OC1, Indonesia North (Batam)
     */
    static readonly AP_BATAM_1: Region;

    /**
     * India South (Chennai)
     */
    static readonly AP_CHENNAI_1: Region;

    /**
     * Realm: OC1, South Korea North (Chuncheon)
     */
    static readonly AP_CHUNCHEON_1: Region;

    /**
     * Realm: OC1, India South (Hyderabad)
     */
    static readonly AP_HYDERABAD_1: Region;

    /**
     * Malaysia West (Kulai)
     */
    static readonly AP_KULAI_1: Region;

    /**
     * Realm: OC1, Australia Southeast (Melbourne)
     */
    static readonly AP_MELBOURNE_1: Region;

    /**
     * Realm: OC1, India West (Mumbai)
     */
    static readonly AP_MUMBAI_1: Region;

    /**
     * Realm: OC1, Japan Central (Osaka)
     */
    static readonly AP_OSAKA_1: Region;

    /**
     * Realm: OC1, South Korea Central (Seoul)
     */
    static readonly AP_SEOUL_1: Region;

    /**
     * Realm: OC1, Singapore (Singapore)
     */
    static readonly AP_SINGAPORE_1: Region;

    /**
     * Realm: OC1, Singapore2 (Singapore)
     */
    static readonly AP_SINGAPORE_2: Region;

    /**
     * Realm: OC1, Australia East (Sydney)
     */
    static readonly AP_SYDNEY_1: Region;

    /**
     * Realm: OC1, Japan East (Tokyo)
     */
    static readonly AP_TOKYO_1: Region;

    /**
     * Realm: OC1, Canada Southeast (Montreal)
     */
    static readonly CA_MONTREAL_1: Region;

    /**
     * Realm: OC1, Canada Southeast (Toronto)
     */
    static readonly CA_TORONTO_1: Region;

    /**
     * Realm: OC1, Netherlands Northwest (Amsterdam)
     */
    static readonly EU_AMSTERDAM_1: Region;

    /**
     * Ireland East (Dublin)
     */
    static readonly EU_DUBLIN_3: Region;

    /**
     * Realm: OC1, Germany Central (Frankfurt)
     */
    static readonly EU_FRANKFURT_1: Region;

    /**
     * Realm: OC1, Spain (Madrid)
     */
    static readonly EU_MADRID_1: Region;

    /**
     * Spain Central (Madrid 3)
     */
    static readonly EU_MADRID_3: Region;

    /**
     * Realm: OC1, France (Marseille)
     */
    static readonly EU_MARSEILLE_1: Region;

    /**
     * Realm: OC1, Italy (Milan)
     */
    static readonly EU_MILAN_1: Region;

    /**
     * Realm: OC1, France (Paris)
     */
    static readonly EU_PARIS_1: Region;

    /**
     * Realm: OC1, Sweden (Stockholm)
     */
    static readonly EU_STOCKHOLM_1: Region;

    /**
     * Italy North (Turin)
     */
    static readonly EU_TURIN_1: Region;

    /**
     * Realm: OC1, Switzerland North (Zurich)
     */
    static readonly EU_ZURICH_1: Region;

    /**
     * Realm: OC1, Israel (Jerusalem)
     */
    static readonly IL_JERUSALEM_1: Region;

    /**
     * Realm: OC1, UAE (Abu Dhabi)
     */
    static readonly ME_ABUDHABI_1: Region;

    /**
     * Realm: OC1, UAE East (Dubai)
     */
    static readonly ME_DUBAI_1: Region;

    /**
     * Realm: OC1, Saudi Arabia West (Jeddah)
     */
    static readonly ME_JEDDAH_1: Region;

    /**
     * Realm: OC1, RegionID: me-riyadh-1, RegionKey: RUH
     */
    static readonly ME_RIYADH_1: Region;

    /**
     * Realm: OC1, Mexico (Monterrey)
     */
    static readonly MX_MONTERREY_1: Region;

    /**
     * Realm: OC1, Mexico (Queretaro)
     */
    static readonly MX_QUERETARO_1: Region;

    /**
     * Realm: OC1, Colombia (Bogota)
     */
    static readonly SA_BOGOTA_1: Region;

    /**
     * Realm: OC1, Chile (Santiago)
     */
    static readonly SA_SANTIAGO_1: Region;

    /**
     * Realm: OC1, Brazil East (Sao Paulo)
     */
    static readonly SA_SAOPAULO_1: Region;

    /**
     * Realm: OC1, Chile (Valparaiso)
     */
    static readonly SA_VALPARAISO_1: Region;

    /**
     * Realm: OC1, Brazil (Vinhedo)
     */
    static readonly SA_VINHEDO_1: Region;

    /**
     * Realm: OC1, UK South (London)
     */
    static readonly UK_LONDON_1: Region;

    /**
     * Realm: OC1, UK West (Newport)
     */
    static readonly UK_CARDIFF_1: Region;

    /**
     * Realm: OC1, US South Central (Abilene)
     */
    static readonly US_ABILENE_1: Region;

    /**
     * US Central (Columbus)
     */
    static readonly US_COLUMBUS_1: Region;

    /**
     * US West (Quincy)
     */
    static readonly US_QUINCY_1: Region;

    /**
     * US West (Boardman)
     */
    static readonly US_BOARDMAN_1: Region;

    /**
     * Realm: OC1, US South (Dallas)
     */
    static readonly US_DALLAS_1: Region;

    /**
     * US Midwest (Des Moines)
     */
    static readonly US_DESMOINES_1: Region;

    /**
     * Realm: OC1, US West (Phoenix)
     */
    static readonly US_PHOENIX_1: Region;

    /**
     * Realm: OC1, US East (Ashburn)
     */
    static readonly US_ASHBURN_1: Region;

    /**
     * Realm: OC1, US West (Salt Lake)
     */
    static readonly US_SALTLAKE_2: Region;

    /**
     * Realm: OC1, US West (San Jose)
     */
    static readonly US_SANJOSE_1: Region;

    /**
     * US Mid West (Shawnee)
     */
    static readonly US_SHAWNEE_1: Region;

    /**
     * Realm: OC1, US Central (Chicago)
     */
    static readonly US_CHICAGO_1: Region;

    /**
     * Realm: OC1, Kulai 2
     */
    static readonly AP_KULAI_2: Region;

    /**
     * Realm: OC1, Delhi 1
     */
    static readonly AP_DELHI_1: Region;

    /**
     * Realm: OC2, US Gov East (Ashburn)
     */
    static readonly US_LANGLEY_1: Region;

    /**
     * Realm: OC2, US Gov West (Phoenix)
     */
    static readonly US_LUKE_1: Region;

    /**
     * Realm: OC3, US DoD East (Ashburn)
     */
    static readonly US_GOV_ASHBURN_1: Region;

    /**
     * Realm: OC3, US DoD North (Chicago)
     */
    static readonly US_GOV_CHICAGO_1: Region;

    /**
     * Realm: OC3, US DoD West (Phoenix)
     */
    static readonly US_GOV_PHOENIX_1: Region;

    /**
     * Realm: OC4, UK Gov South (London)
     */
    static readonly UK_GOV_LONDON_1: Region;

    /**
     * Realm: OC4, UK Gov West (Cardiff)
     */
    static readonly UK_GOV_CARDIFF_1: Region;

    /**
     * Realm: OC5, US West (Tacoma)
     */
    static readonly US_TACOMA_1: Region;

    /**
     * Realm: OC8, Japan East (Chiyoda)
     */
    static readonly AP_CHIYODA_1: Region;

    /**
     * Realm: OC8, Japan East (Ibaraki) (Note: OCI uses 'ukb' instead of 'ibr')
     */
    static readonly AP_IBARAKI_1: Region;

    /**
     * Realm: OC9, Muscat (Dedicated DataCenter)
     */
    static readonly ME_DCC_MUSCAT_1: Region;

    /**
     * Realm: OC9, Ibri 1
     */
    static readonly ME_IBRI_1: Region;

    /**
     * Realm: OC10, Canberra (Dedicated DataCenter)
     */
    static readonly AP_DCC_CANBERRA_1: Region;

    /**
     * Realm: OC14, Dublin 1 (Dedicated DataCenter)
     */
    static readonly EU_DCC_DUBLIN_1: Region;

    /**
     * Realm: OC14, Dublin 2 (Dedicated DataCenter)
     */
    static readonly EU_DCC_DUBLIN_2: Region;

    /**
     * Realm: OC14, Milan 1 (Dedicated DataCenter)
     */
    static readonly EU_DCC_MILAN_1: Region;

    /**
     * Realm: OC14, Milan 2 (Dedicated DataCenter)
     */
    static readonly EU_DCC_MILAN_2: Region;

    /**
     * Realm: OC14, Rating 1 (Dedicated DataCenter)
     */
    static readonly EU_DCC_RATING_1: Region;

    /**
     * Realm: OC14, Rating 2 (Dedicated DataCenter)
     */
    static readonly EU_DCC_RATING_2: Region;

    /**
     * Realm: OC15, Bangladesh
     */
    static readonly AP_DCC_GAZIPUR_1: Region;

    /**
     * Realm: OC16, US West (Utah)
     */
    static readonly US_WESTJORDAN_1: Region;

    /**
     * Realm: OC17, Phoenix 1 (Dedicated DataCenter)
     */
    static readonly US_DCC_PHOENIX_1: Region;

    /**
     * Realm: OC17, Phoenix 2 (Dedicated DataCenter)
     */
    static readonly US_DCC_PHOENIX_2: Region;

    /**
     * Realm: OC17, Phoenix 4 (Dedicated DataCenter)
     */
    static readonly US_DCC_PHOENIX_4: Region;

    /**
     * Realm: OC19, Frankfurt (Germany)
     */
    static readonly EU_FRANKFURT_2: Region;

    /**
     * Realm: OC19, Madrid (Spain)
     */
    static readonly EU_MADRID_2: Region;

    /**
     * Realm: OC20, Jovanovac (Serbia)
     */
    static readonly EU_JOVANOVAC_1: Region;

    /**
     * Realm: OC21, Doha (Qatar)
     */
    static readonly ME_DCC_DOHA_1: Region;

    /**
     * Realm: OC22, PSN Region Rome
     */
    static readonly EU_DCC_ROME_1: Region;

    /**
     * Realm: OC22, PSN Region Milan
     */
    static readonly EU_MILAN_2: Region;

    /**
     * Realm: OC23, RegionID: us-somerset-1, RegionKey: EBB
     */
    static readonly US_SOMERSET_1: Region;

    /**
     * Realm: OC23, RegionID: us-thames-1, RegionKey: EBL
     */
    static readonly US_THAMES_1: Region;

    /**
     * Realm: OC24, Switzerland dedicated (Zurich)
     */
    static readonly EU_DCC_ZURICH_1: Region;

    /**
     * Realm: OC24, RegionID: eu-crissier-1, RegionKey: AVF
     */
    static readonly EU_CRISSIER_1: Region;

    /**
     * Realm: OC25, Japan dedicated (Osaka)
     */
    static readonly AP_DCC_OSAKA_1: Region;

    /**
     * Realm: OC25, Japan dedicated (Tokyo)
     */
    static readonly AP_DCC_TOKYO_1: Region;

    /**
     * Realm: OC26, Abudhabi
     */
    static readonly ME_ABUDHABI_3: Region;

    /**
     * Realm: OC26, RegionID: me-alain-1, RegionKey: RBA
     */
    static readonly ME_ALAIN_1: Region;

    /**
     * Realm: OC27, SWJordan dedicated (Utah USA)
     */
    static readonly US_DCC_SWJORDAN_1: Region;

    /**
     * Realm: OC28, SWJordan dedicated (Utah USA)
     */
    static readonly US_DCC_SWJORDAN_2: Region;

    /**
     * Realm: OC29, Abudhabi 2
     */
    static readonly ME_ABUDHABI_2: Region;

    /**
     * Realm: OC29, Abudhabi 4
     */
    static readonly ME_ABUDHABI_4: Region;

    /**
     * Realm: OC31, Hobsonville dedicated (New Zealand)
     */
    static readonly AP_HOBSONVILLE_1: Region;

    /**
     * Realm: OC31, Silverdale dedicated (New Zealand)
     */
    static readonly AP_SILVERDALE_1: Region;

    /**
     * Realm: OC35, South Korea North (Suwon)
     */
    static readonly AP_SUWON_1: Region;

    /**
     * Realm: OC35, South Korea North (Seoul)
     */
    static readonly AP_SEOUL_2: Region;

    /**
     * Realm: OC35, South Korea North (Chuncheon)
     */
    static readonly AP_CHUNCHEON_2: Region;

    /**
     * Riyadh 2 Alloy
     */
    static readonly ME_RIYADH_2: Region;

    /**
     * Realm: OC39, Butterfly Stable
     */
    static readonly US_TUKWILA_3: Region;

    /**
     * Realm: OC40, Sovereign Cloud (Japan West)
     */
    static readonly AP_OSAKA_2: Region;

    /**
     * Realm: OC40, Sovereign Cloud
     */
    static readonly AP_TATEBAYASHI_1: Region;

    /**
     * Realm: OC41, UAE North 1
     */
    static readonly ME_DUBAI_3: Region;

    /**
     * Newark 1 DRCC
     */
    static readonly US_NEWARK_1: Region;

    /**
     * Realm: OC43, Thailand 1 (AIS)
     */
    static readonly AP_PATHUMTHANI_1: Region;

    /**
     * Thailand 2 (AIS)
     */
    static readonly AP_SAMUTPRAKAN_1: Region;

    /**
     * Realm: OC46, Butterfly Lab 1
     */
    static readonly UK_LONDON_2: Region;

    /**
     * Realm: OC47, Butterfly Lab 2
     */
    static readonly UK_LONDON_3: Region;

    /**
     * Realm: OC47, London 4
     */
    static readonly UK_LONDON_4: Region;

    /**
     * Realm: OC51, Budapest
     */
    static readonly EU_BUDAPEST_1: Region;

    /**
     * Realm: OC52, Rio De Janeiro
     */
    static readonly SA_RIODEJANEIRO_1: Region;

    /**
     * WestTokyo 1 Alloy
     */
    static readonly AP_WESTTOKYO_1: Region;

    /**
     * Realm: OC57, Abu Dhabi 5
     */
    static readonly ME_ABUDHABI_5: Region;

    /**
     * Realm: OC57, Dubai 4
     */
    static readonly ME_DUBAI_4: Region;

    /* === End autogenerated realms and regions === */
}
