/*-
 * Copyright (c) 2018, 2026 Oracle and/or its affiliates. All rights reserved.
 *
 * Licensed under the Universal Permissive License v 1.0 as shown at
 *  https://oss.oracle.com/licenses/upl/
 */

import type { Config } from "./config";

/**
 * Cloud service only.
 * <p>
 * This enumeration lists all regions available for Oracle NoSQL Database
 * Cloud Service.
 * {@link https://docs.cloud.oracle.com/iaas/Content/General/Concepts/regions.htm | This page}
 * provides information about Oracle Cloud Infrastracture regions,
 * availability domains and realms.
 * <p>
 * You may use {@link Region} to provide the service endpoint by specifying
 * {@link Config#region} instead of {@link Config#endpoint}. The endpoint will
 * be inferred from the region. Use of a {@link Region} instance is preferred
 * to an endpoint.
 * <p>
 * The string-based endpoints associated with regions for the Oracle NoSQL
 * Database Cloud Service are of the format
 * <pre> https://nosql.\{region\}.oci.\{secondLevelDomain\} </pre>
 * Examples of known second level domains include:
 * <ul>
 * <li>oraclecloud.com</li>
 * <li>oraclegovcloud.com</li>
 * <li>oraclegovcloud.uk</li>
 * </ul>
 * For example, this is a valid endpoint for the Oracle NoSQL Database Cloud
 * Service in the U.S. East region
 * <pre>    nosql.us-ashburn-1.oci.oraclecloud.com </pre>
 * If the Oracle NoSQL Database Cloud Service becomes available in a region
 * not listed here it is possible to connect to that region by setting
 * {@link Config#endpoint} to the endpoint string.
 *
 * @see {@link Config}
 */
export class Region {

    /**
     * @hidden
     */
    private constructor();

    /**
     * Array of all region values.
     */
    static readonly values: Region[];

    /**
     * Get region by region id.
     * @param {string} regionId Region id, e.g. ap-mumbai-1
     * @return {Region} The region, or <em>undefined</em> if given region id
     * is not found.
     */
    static fromRegionId(regionId: string): Region|undefined;

    /**
     * Get region by region code or id.
     * @param {string} regionId Region id, e.g. bom or ap-mumbai-1
     * @return {Region} The region, or <em>undefined</em> if given region code
     * or id is not found.
     */
    static fromRegionCodeOrId(regionCodeOrId: string): Region|undefined;
    
    /**
     * NoSQL service endpoint for this region.
     */
    readonly endpoint: string;

     /**
     * Region id, e.g. <em>ap-mumbai-1</em>.
     */
    readonly regionId: string;
    
    /**
     * Region 3-letter code, e.g. <em>bom</em>.
     */
    readonly regionCode: string;

    /**
     * Second-level domain for the region, e.g. <em>oraclecloud.com</em>.
     */
    readonly secondLevelDomain: string;

    /**
     * Returns string representing this region.
     * @returns String representation, which is {@link regionId}
     */
    toString(): string;

    /* === Begin autogenerated realms and regions === */
    /**
     * Realm: OC0, RegionID: uk-london-9, RegionKey: AEJ
     */
    static readonly UK_LONDON_9: Region;

    /**
     * Realm: OC0, RegionID: us-renton-1, RegionKey: RNT
     */
    static readonly US_RENTON_1: Region;

    /**
     * Realm: OC0, RegionID: us-scottsdale-1, RegionKey: SCF
     */
    static readonly US_SCOTTSDALE_1: Region;

    /**
     * Realm: OC1, RegionID: af-casablanca-1, RegionKey: LEJ
     */
    static readonly AF_CASABLANCA_1: Region;

    /**
     * Realm: OC1, RegionID: af-johannesburg-1, RegionKey: JNB
     */
    static readonly AF_JOHANNESBURG_1: Region;

    /**
     * Realm: OC1, RegionID: af-nairobi-1, RegionKey: KXT
     */
    static readonly AF_NAIROBI_1: Region;

    /**
     * Realm: OC1, RegionID: ap-batam-1, RegionKey: HSG
     */
    static readonly AP_BATAM_1: Region;

    /**
     * Realm: OC1, RegionID: ap-chennai-1, RegionKey: DES
     */
    static readonly AP_CHENNAI_1: Region;

    /**
     * Realm: OC1, RegionID: ap-chuncheon-1, RegionKey: YNY
     */
    static readonly AP_CHUNCHEON_1: Region;

    /**
     * Realm: OC1, RegionID: ap-delhi-1, RegionKey: ONM
     */
    static readonly AP_DELHI_1: Region;

    /**
     * Realm: OC1, RegionID: ap-hyderabad-1, RegionKey: HYD
     */
    static readonly AP_HYDERABAD_1: Region;

    /**
     * Realm: OC1, RegionID: ap-kulai-1, RegionKey: FYV
     */
    static readonly AP_KULAI_1: Region;

    /**
     * Realm: OC1, RegionID: ap-kulai-2, RegionKey: JBP
     */
    static readonly AP_KULAI_2: Region;

    /**
     * Realm: OC1, RegionID: ap-melbourne-1, RegionKey: MEL
     */
    static readonly AP_MELBOURNE_1: Region;

    /**
     * Realm: OC1, RegionID: ap-mumbai-1, RegionKey: BOM
     */
    static readonly AP_MUMBAI_1: Region;

    /**
     * Realm: OC1, RegionID: ap-osaka-1, RegionKey: KIX
     */
    static readonly AP_OSAKA_1: Region;

    /**
     * Realm: OC1, RegionID: ap-seoul-1, RegionKey: ICN
     */
    static readonly AP_SEOUL_1: Region;

    /**
     * Realm: OC1, RegionID: ap-singapore-1, RegionKey: SIN
     */
    static readonly AP_SINGAPORE_1: Region;

    /**
     * Realm: OC1, RegionID: ap-singapore-2, RegionKey: XSP
     */
    static readonly AP_SINGAPORE_2: Region;

    /**
     * Realm: OC1, RegionID: ap-sydney-1, RegionKey: SYD
     */
    static readonly AP_SYDNEY_1: Region;

    /**
     * Realm: OC1, RegionID: ap-tokyo-1, RegionKey: NRT
     */
    static readonly AP_TOKYO_1: Region;

    /**
     * Realm: OC1, RegionID: ca-montreal-1, RegionKey: YUL
     */
    static readonly CA_MONTREAL_1: Region;

    /**
     * Realm: OC1, RegionID: ca-toronto-1, RegionKey: YYZ
     */
    static readonly CA_TORONTO_1: Region;

    /**
     * Realm: OC1, RegionID: eu-amsterdam-1, RegionKey: AMS
     */
    static readonly EU_AMSTERDAM_1: Region;

    /**
     * Realm: OC1, RegionID: eu-dublin-3, RegionKey: ZQO
     */
    static readonly EU_DUBLIN_3: Region;

    /**
     * Realm: OC1, RegionID: eu-frankfurt-1, RegionKey: FRA
     */
    static readonly EU_FRANKFURT_1: Region;

    /**
     * Realm: OC1, RegionID: eu-madrid-1, RegionKey: MAD
     */
    static readonly EU_MADRID_1: Region;

    /**
     * Realm: OC1, RegionID: eu-madrid-3, RegionKey: ORF
     */
    static readonly EU_MADRID_3: Region;

    /**
     * Realm: OC1, RegionID: eu-marseille-1, RegionKey: MRS
     */
    static readonly EU_MARSEILLE_1: Region;

    /**
     * Realm: OC1, RegionID: eu-milan-1, RegionKey: LIN
     */
    static readonly EU_MILAN_1: Region;

    /**
     * Realm: OC1, RegionID: eu-paris-1, RegionKey: CDG
     */
    static readonly EU_PARIS_1: Region;

    /**
     * Realm: OC1, RegionID: eu-stockholm-1, RegionKey: ARN
     */
    static readonly EU_STOCKHOLM_1: Region;

    /**
     * Realm: OC1, RegionID: eu-turin-1, RegionKey: NRQ
     */
    static readonly EU_TURIN_1: Region;

    /**
     * Realm: OC1, RegionID: eu-zurich-1, RegionKey: ZRH
     */
    static readonly EU_ZURICH_1: Region;

    /**
     * Realm: OC1, RegionID: il-jerusalem-1, RegionKey: MTZ
     */
    static readonly IL_JERUSALEM_1: Region;

    /**
     * Realm: OC1, RegionID: me-abudhabi-1, RegionKey: AUH
     */
    static readonly ME_ABUDHABI_1: Region;

    /**
     * Realm: OC1, RegionID: me-dubai-1, RegionKey: DXB
     */
    static readonly ME_DUBAI_1: Region;

    /**
     * Realm: OC1, RegionID: me-jeddah-1, RegionKey: JED
     */
    static readonly ME_JEDDAH_1: Region;

    /**
     * Realm: OC1, RegionID: me-riyadh-1, RegionKey: RUH
     */
    static readonly ME_RIYADH_1: Region;

    /**
     * Realm: OC1, RegionID: mx-monterrey-1, RegionKey: MTY
     */
    static readonly MX_MONTERREY_1: Region;

    /**
     * Realm: OC1, RegionID: mx-queretaro-1, RegionKey: QRO
     */
    static readonly MX_QUERETARO_1: Region;

    /**
     * Realm: OC1, RegionID: sa-bogota-1, RegionKey: BOG
     */
    static readonly SA_BOGOTA_1: Region;

    /**
     * Realm: OC1, RegionID: sa-riodejaneiro-2, RegionKey: SWQ
     */
    static readonly SA_RIODEJANEIRO_2: Region;

    /**
     * Realm: OC1, RegionID: sa-santiago-1, RegionKey: SCL
     */
    static readonly SA_SANTIAGO_1: Region;

    /**
     * Realm: OC1, RegionID: sa-saopaulo-1, RegionKey: GRU
     */
    static readonly SA_SAOPAULO_1: Region;

    /**
     * Realm: OC1, RegionID: sa-valparaiso-1, RegionKey: VAP
     */
    static readonly SA_VALPARAISO_1: Region;

    /**
     * Realm: OC1, RegionID: sa-vinhedo-1, RegionKey: VCP
     */
    static readonly SA_VINHEDO_1: Region;

    /**
     * Realm: OC1, RegionID: uk-cardiff-1, RegionKey: CWL
     */
    static readonly UK_CARDIFF_1: Region;

    /**
     * Realm: OC1, RegionID: uk-london-1, RegionKey: LHR
     */
    static readonly UK_LONDON_1: Region;

    /**
     * Realm: OC1, RegionID: us-abilene-1, RegionKey: ABL
     */
    static readonly US_ABILENE_1: Region;

    /**
     * Realm: OC1, RegionID: us-ashburn-1, RegionKey: IAD
     */
    static readonly US_ASHBURN_1: Region;

    /**
     * Realm: OC1, RegionID: us-boardman-1, RegionKey: NHJ
     */
    static readonly US_BOARDMAN_1: Region;

    /**
     * Realm: OC1, RegionID: us-chicago-1, RegionKey: ORD
     */
    static readonly US_CHICAGO_1: Region;

    /**
     * Realm: OC1, RegionID: us-columbus-1, RegionKey: VKZ
     */
    static readonly US_COLUMBUS_1: Region;

    /**
     * Realm: OC1, RegionID: us-dallas-1, RegionKey: DFW
     */
    static readonly US_DALLAS_1: Region;

    /**
     * Realm: OC1, RegionID: us-desmoines-1, RegionKey: KQQ
     */
    static readonly US_DESMOINES_1: Region;

    /**
     * Realm: OC1, RegionID: us-lenexa-1, RegionKey: LXO
     */
    static readonly US_LENEXA_1: Region;

    /**
     * Realm: OC1, RegionID: us-phoenix-1, RegionKey: PHX
     */
    static readonly US_PHOENIX_1: Region;

    /**
     * Realm: OC1, RegionID: us-quincy-1, RegionKey: EEM
     */
    static readonly US_QUINCY_1: Region;

    /**
     * Realm: OC1, RegionID: us-saltlake-2, RegionKey: AGA
     */
    static readonly US_SALTLAKE_2: Region;

    /**
     * Realm: OC1, RegionID: us-sanantonio-1, RegionKey: FBB
     */
    static readonly US_SANANTONIO_1: Region;

    /**
     * Realm: OC1, RegionID: us-sanjose-1, RegionKey: SJC
     */
    static readonly US_SANJOSE_1: Region;

    /**
     * Realm: OC1, RegionID: us-shawnee-1, RegionKey: DRZ
     */
    static readonly US_SHAWNEE_1: Region;

    /**
     * Realm: OC2, RegionID: us-langley-1, RegionKey: LFI
     */
    static readonly US_LANGLEY_1: Region;

    /**
     * Realm: OC2, RegionID: us-luke-1, RegionKey: LUF
     */
    static readonly US_LUKE_1: Region;

    /**
     * Realm: OC3, RegionID: us-gov-ashburn-1, RegionKey: RIC
     */
    static readonly US_GOV_ASHBURN_1: Region;

    /**
     * Realm: OC3, RegionID: us-gov-chicago-1, RegionKey: PIA
     */
    static readonly US_GOV_CHICAGO_1: Region;

    /**
     * Realm: OC3, RegionID: us-gov-phoenix-1, RegionKey: TUS
     */
    static readonly US_GOV_PHOENIX_1: Region;

    /**
     * Realm: OC4, RegionID: uk-gov-cardiff-1, RegionKey: BRS
     */
    static readonly UK_GOV_CARDIFF_1: Region;

    /**
     * Realm: OC4, RegionID: uk-gov-london-1, RegionKey: LTN
     */
    static readonly UK_GOV_LONDON_1: Region;

    /**
     * Realm: OC5, RegionID: us-tacoma-1, RegionKey: TIW
     */
    static readonly US_TACOMA_1: Region;

    /**
     * Realm: OC6, RegionID: us-gov-fortworth-1, RegionKey: FTW
     */
    static readonly US_GOV_FORTWORTH_1: Region;

    /**
     * Realm: OC6, RegionID: us-gov-sterling-2, RegionKey: DCA
     */
    static readonly US_GOV_STERLING_2: Region;

    /**
     * Realm: OC8, RegionID: ap-chiyoda-1, RegionKey: NJA
     */
    static readonly AP_CHIYODA_1: Region;

    /**
     * Realm: OC8, RegionID: ap-ibaraki-1, RegionKey: UKB
     */
    static readonly AP_IBARAKI_1: Region;

    /**
     * Realm: OC9, RegionID: me-dcc-muscat-1, RegionKey: MCT
     */
    static readonly ME_DCC_MUSCAT_1: Region;

    /**
     * Realm: OC9, RegionID: me-ibri-1, RegionKey: IBR
     */
    static readonly ME_IBRI_1: Region;

    /**
     * Realm: OC10, RegionID: ap-dcc-canberra-1, RegionKey: WGA
     */
    static readonly AP_DCC_CANBERRA_1: Region;

    /**
     * Realm: OC11, RegionID: us-gov-fortworth-3, RegionKey: DAL
     */
    static readonly US_GOV_FORTWORTH_3: Region;

    /**
     * Realm: OC11, RegionID: us-gov-phoenix-3, RegionKey: GYR
     */
    static readonly US_GOV_PHOENIX_3: Region;

    /**
     * Realm: OC11, RegionID: us-gov-sterling-3, RegionKey: HEF
     */
    static readonly US_GOV_STERLING_3: Region;

    /**
     * Realm: OC12, RegionID: us-gov-ashburn-2, RegionKey: OKV
     */
    static readonly US_GOV_ASHBURN_2: Region;

    /**
     * Realm: OC12, RegionID: us-gov-phoenix-2, RegionKey: GEU
     */
    static readonly US_GOV_PHOENIX_2: Region;

    /**
     * Realm: OC12, RegionID: us-gov-saltlake-1, RegionKey: VEL
     */
    static readonly US_GOV_SALTLAKE_1: Region;

    /**
     * Realm: OC14, RegionID: eu-dcc-dublin-1, RegionKey: ORK
     */
    static readonly EU_DCC_DUBLIN_1: Region;

    /**
     * Realm: OC14, RegionID: eu-dcc-dublin-2, RegionKey: SNN
     */
    static readonly EU_DCC_DUBLIN_2: Region;

    /**
     * Realm: OC14, RegionID: eu-dcc-milan-1, RegionKey: BGY
     */
    static readonly EU_DCC_MILAN_1: Region;

    /**
     * Realm: OC14, RegionID: eu-dcc-milan-2, RegionKey: MXP
     */
    static readonly EU_DCC_MILAN_2: Region;

    /**
     * Realm: OC14, RegionID: eu-dcc-rating-1, RegionKey: DUS
     */
    static readonly EU_DCC_RATING_1: Region;

    /**
     * Realm: OC14, RegionID: eu-dcc-rating-2, RegionKey: DTM
     */
    static readonly EU_DCC_RATING_2: Region;

    /**
     * Realm: OC15, RegionID: ap-dcc-gazipur-1, RegionKey: DAC
     */
    static readonly AP_DCC_GAZIPUR_1: Region;

    /**
     * Realm: OC16, RegionID: us-sanjose-2, RegionKey: QKL
     */
    static readonly US_SANJOSE_2: Region;

    /**
     * Realm: OC16, RegionID: us-westjordan-1, RegionKey: SGU
     */
    static readonly US_WESTJORDAN_1: Region;

    /**
     * Realm: OC17, RegionID: us-dcc-phoenix-1, RegionKey: IFP
     */
    static readonly US_DCC_PHOENIX_1: Region;

    /**
     * Realm: OC17, RegionID: us-dcc-phoenix-2, RegionKey: GCN
     */
    static readonly US_DCC_PHOENIX_2: Region;

    /**
     * Realm: OC17, RegionID: us-dcc-phoenix-4, RegionKey: YUM
     */
    static readonly US_DCC_PHOENIX_4: Region;

    /**
     * Realm: OC19, RegionID: eu-frankfurt-2, RegionKey: STR
     */
    static readonly EU_FRANKFURT_2: Region;

    /**
     * Realm: OC19, RegionID: eu-madrid-2, RegionKey: VLL
     */
    static readonly EU_MADRID_2: Region;

    /**
     * Realm: OC20, RegionID: eu-jovanovac-1, RegionKey: BEG
     */
    static readonly EU_JOVANOVAC_1: Region;

    /**
     * Realm: OC21, RegionID: me-alrayyan-1, RegionKey: VVE
     */
    static readonly ME_ALRAYYAN_1: Region;

    /**
     * Realm: OC21, RegionID: me-dcc-doha-1, RegionKey: DOH
     */
    static readonly ME_DCC_DOHA_1: Region;

    /**
     * Realm: OC22, RegionID: eu-dcc-rome-1, RegionKey: NAP
     */
    static readonly EU_DCC_ROME_1: Region;

    /**
     * Realm: OC22, RegionID: eu-milan-2, RegionKey: PBV
     */
    static readonly EU_MILAN_2: Region;

    /**
     * Realm: OC23, RegionID: us-somerset-1, RegionKey: EBB
     */
    static readonly US_SOMERSET_1: Region;

    /**
     * Realm: OC23, RegionID: us-thames-1, RegionKey: EBL
     */
    static readonly US_THAMES_1: Region;

    /**
     * Realm: OC24, RegionID: eu-crissier-1, RegionKey: AVF
     */
    static readonly EU_CRISSIER_1: Region;

    /**
     * Realm: OC24, RegionID: eu-dcc-zurich-1, RegionKey: AVZ
     */
    static readonly EU_DCC_ZURICH_1: Region;

    /**
     * Realm: OC25, RegionID: ap-dcc-osaka-1, RegionKey: UKY
     */
    static readonly AP_DCC_OSAKA_1: Region;

    /**
     * Realm: OC25, RegionID: ap-dcc-tokyo-1, RegionKey: TYO
     */
    static readonly AP_DCC_TOKYO_1: Region;

    /**
     * Realm: OC26, RegionID: me-abudhabi-3, RegionKey: AHU
     */
    static readonly ME_ABUDHABI_3: Region;

    /**
     * Realm: OC26, RegionID: me-alain-1, RegionKey: RBA
     */
    static readonly ME_ALAIN_1: Region;

    /**
     * Realm: OC27, RegionID: us-dcc-swjordan-1, RegionKey: OZZ
     */
    static readonly US_DCC_SWJORDAN_1: Region;

    /**
     * Realm: OC28, RegionID: us-dcc-swjordan-2, RegionKey: DRS
     */
    static readonly US_DCC_SWJORDAN_2: Region;

    /**
     * Realm: OC29, RegionID: me-abudhabi-2, RegionKey: RKT
     */
    static readonly ME_ABUDHABI_2: Region;

    /**
     * Realm: OC29, RegionID: me-abudhabi-4, RegionKey: SHJ
     */
    static readonly ME_ABUDHABI_4: Region;

    /**
     * Realm: OC31, RegionID: ap-hobsonville-1, RegionKey: IZQ
     */
    static readonly AP_HOBSONVILLE_1: Region;

    /**
     * Realm: OC31, RegionID: ap-silverdale-1, RegionKey: JJT
     */
    static readonly AP_SILVERDALE_1: Region;

    /**
     * Realm: OC32, RegionID: ap-olympic-1, RegionKey: ZZM
     */
    static readonly AP_OLYMPIC_1: Region;

    /**
     * Realm: OC35, RegionID: ap-chuncheon-2, RegionKey: BNO
     */
    static readonly AP_CHUNCHEON_2: Region;

    /**
     * Realm: OC35, RegionID: ap-seoul-2, RegionKey: DTZ
     */
    static readonly AP_SEOUL_2: Region;

    /**
     * Realm: OC35, RegionID: ap-suwon-1, RegionKey: DLN
     */
    static readonly AP_SUWON_1: Region;

    /**
     * Realm: OC36, RegionID: me-alkhobar-1, RegionKey: DAM
     */
    static readonly ME_ALKHOBAR_1: Region;

    /**
     * Realm: OC36, RegionID: me-riyadh-2, RegionKey: KZQ
     */
    static readonly ME_RIYADH_2: Region;

    /**
     * Realm: OC39, RegionID: us-tukwila-3, RegionKey: NBQ
     */
    static readonly US_TUKWILA_3: Region;

    /**
     * Realm: OC40, RegionID: ap-osaka-2, RegionKey: IBG
     */
    static readonly AP_OSAKA_2: Region;

    /**
     * Realm: OC40, RegionID: ap-tatebayashi-1, RegionKey: JBB
     */
    static readonly AP_TATEBAYASHI_1: Region;

    /**
     * Realm: OC41, RegionID: me-dubai-2, RegionKey: ABR
     */
    static readonly ME_DUBAI_2: Region;

    /**
     * Realm: OC41, RegionID: me-dubai-3, RegionKey: PCZ
     */
    static readonly ME_DUBAI_3: Region;

    /**
     * Realm: OC42, RegionID: us-ashburn-2, RegionKey: YXJ
     */
    static readonly US_ASHBURN_2: Region;

    /**
     * Realm: OC42, RegionID: us-newark-1, RegionKey: PGC
     */
    static readonly US_NEWARK_1: Region;

    /**
     * Realm: OC43, RegionID: ap-pathumthani-1, RegionKey: MEZ
     */
    static readonly AP_PATHUMTHANI_1: Region;

    /**
     * Realm: OC43, RegionID: ap-samutprakan-1, RegionKey: YIK
     */
    static readonly AP_SAMUTPRAKAN_1: Region;

    /**
     * Realm: OC45, RegionID: me-sabahiya-1, RegionKey: AYZ
     */
    static readonly ME_SABAHIYA_1: Region;

    /**
     * Realm: OC46, RegionID: uk-london-2, RegionKey: DEN
     */
    static readonly UK_LONDON_2: Region;

    /**
     * Realm: OC47, RegionID: uk-london-3, RegionKey: KAL
     */
    static readonly UK_LONDON_3: Region;

    /**
     * Realm: OC47, RegionID: uk-london-4, RegionKey: PYZ
     */
    static readonly UK_LONDON_4: Region;

    /**
     * Realm: OC50, RegionID: ap-kyoto-1, RegionKey: SUF
     */
    static readonly AP_KYOTO_1: Region;

    /**
     * Realm: OC50, RegionID: ap-mitaka-1, RegionKey: MFQ
     */
    static readonly AP_MITAKA_1: Region;

    /**
     * Realm: OC51, RegionID: eu-budapest-1, RegionKey: JSK
     */
    static readonly EU_BUDAPEST_1: Region;

    /**
     * Realm: OC52, RegionID: sa-riodejaneiro-1, RegionKey: HNW
     */
    static readonly SA_RIODEJANEIRO_1: Region;

    /**
     * Realm: OC54, RegionID: sa-belenzinho-1, RegionKey: TRX
     */
    static readonly SA_BELENZINHO_1: Region;

    /**
     * Realm: OC54, RegionID: sa-saopaulo-3, RegionKey: LMP
     */
    static readonly SA_SAOPAULO_3: Region;

    /**
     * Realm: OC55, RegionID: ap-eastosaka-1, RegionKey: DQF
     */
    static readonly AP_EASTOSAKA_1: Region;

    /**
     * Realm: OC55, RegionID: ap-westtokyo-1, RegionKey: ZWE
     */
    static readonly AP_WESTTOKYO_1: Region;

    /**
     * Realm: OC57, RegionID: me-abudhabi-5, RegionKey: JHZ
     */
    static readonly ME_ABUDHABI_5: Region;

    /**
     * Realm: OC57, RegionID: me-dubai-4, RegionKey: ZQA
     */
    static readonly ME_DUBAI_4: Region;

    /**
     * Realm: OC60, RegionID: us-tukwila-5, RegionKey: XAD
     */
    static readonly US_TUKWILA_5: Region;

    /**
     * Realm: OC61, RegionID: us-tukwila-6, RegionKey: XAB
     */
    static readonly US_TUKWILA_6: Region;

    /**
     * Realm: OC62, RegionID: us-tukwila-7, RegionKey: XAC
     */
    static readonly US_TUKWILA_7: Region;

    /**
     * Realm: OC64, RegionID: ap-tokyo-2, RegionKey: JCU
     */
    static readonly AP_TOKYO_2: Region;

    /**
     * Realm: OC88, RegionID: ap-olympic-2, RegionKey: JDX
     */
    static readonly AP_OLYMPIC_2: Region;

    /* === End autogenerated realms and regions === */
}
